webserver:
  port: -1
required: true
hostName: 0.0.0.0

# Not implemented
#custom-host: false
#CUSTOM:
#  upload: https://insertapi.com/upload
#  download: http://insertapi.com/upload/%s
#  auth: XXXX-XXXX-XXXX-XXXX