name: DynamicRP
version: '1.0-SNAPSHOT'
main: de.cjdev.dynamicrp.DynamicRP
api-version: '1.21'
load: STARTUP
authors: [ CJDev ]
description: A Plugin designed to make Dynamic Resource Packs easy
website: https://modrinth.com/project/dynamic-rp
